get_content_url: gracefully handle the lxml errors
Traceback (most recent call last):
  File "/home/macbre/github/mbc-harvest/harvest.py", line 155, in main
    content_url = get_content_url(record)
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macbre/github/mbc-harvest/dlibra.py", line 97, in get_content_url
    if resp.xml is None:
       ^^^^^^^^
  File "/home/macbre/github/mbc-harvest/env/lib/python3.12/site-packages/sickle/response.py", line 37, in xml
    return etree.XML(self.http_response.content,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/lxml/etree.pyx", line 3285, in lxml.etree.XML
  File "src/lxml/parser.pxi", line 1995, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1882, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1164, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 633, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 743, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 672, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1